version: '3'

volumes:
  postgres-db:

services:
  node-server:
    container_name: blog-backend
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./src
        target: /home/node/app/src
    command: npm run start:dev

  db:
    container_name: blog-db
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    container_name: blog-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
